# Generated by Django 4.2.1 on 2023-05-24 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('landpic', models.ImageField(upload_to='uploads/')),
                ('created_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
